[bounty] Add "Informe del responsable de mantenimiento de BCHN 15-04-2020" article
bitcoin-cash-node/bchnode-web pull request #103
Opened 2020-09-10 13:44 UTC by merc1er

#66

2020-09-10 18:26 UTC, ftrader requested changes
Only one change requested (include the translator reference at top)

2020-09-10 18:28 UTC, ftrader commented on blog/Informe-del-responsable-de-mantenimiento-de-BCHN-15-04-2020.md
> +
Should include

> (Esta es una traducción realizada por [Grido](https://read.cash/@Grido) del artículo [original](https://bitcoincashnode.org/en/newsroom/BCHN-lead-maintainer-report-2020-04-15) en inglés.)

2020-09-11 05:32 UTC, merc1er commented
> Only one change requested (include the translator reference at top)

Updated

2020-09-11 10:14 UTC, ftrader approved these changes

2020-09-11 10:14 UTC, ftrader commented
LGTM, bounty awarded to @merc1er

2020-09-11 10:14 UTC, merged